# If enabled, the plugin will attempt to hook into Vault.
# Having this disabled may disable some features in other plugins.
vault: true

# Configure whether custom event are fired
custom-events:
  # PlayerMoveChunkEvent
  move-chunk: true
  # PlayerMoveBlockEvent
  move-block: true

# DO NOT TOUCH THIS VALUE!!!
config-version: 1